// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeL2x9PVYmh2-CIjWS9NMjM7DXndSjLRg',
    appId: '1:582238125490:web:b8fc181ce700b006f678ab',
    messagingSenderId: '582238125490',
    projectId: 'mobile-specs-4a3c3',
    authDomain: 'mobile-specs-4a3c3.firebaseapp.com',
    storageBucket: 'mobile-specs-4a3c3.firebasestorage.app',
    measurementId: 'G-5WHVK3CW9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAygLSwbMTWue_0RbYBmqRi3i8ZZk1QE2s',
    appId: '1:582238125490:android:f0f1873be4399392f678ab',
    messagingSenderId: '582238125490',
    projectId: 'mobile-specs-4a3c3',
    storageBucket: 'mobile-specs-4a3c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUX5G4chYcEI700uTca5Ez7kSLElxsJzc',
    appId: '1:582238125490:ios:f923f59b67cb1f18f678ab',
    messagingSenderId: '582238125490',
    projectId: 'mobile-specs-4a3c3',
    storageBucket: 'mobile-specs-4a3c3.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM_CGsLHdJHhmWPmB5zJHfSxUQdUVGkKE',
    appId: '1:582238125490:web:aaf589babf196736f678ab',
    messagingSenderId: '582238125490',
    projectId: 'mobile-specs-4a3c3',
    authDomain: 'mobile-specs-4a3c3.firebaseapp.com',
    storageBucket: 'mobile-specs-4a3c3.firebasestorage.app',
    measurementId: 'G-PXKEXCZ08Y',
  );

}